# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{ imports =

[(modulesPath + "/installer/scan/not-detected.nix")];

boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
boot.initrd.kernelModules = [ ];
boot.kernelModules = [ "kvm-intel" ];
boot.extraModulePackages = [ ];

nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
hardware.cpu.intel.updateMicrocode = lib.mkDefault   config.hardware.enableRedistributableFirmware;

hardware.graphics = {
  enable = true;
  extraPackages = with pkgs; [
    # Required for modern Intel GPUs (Xe iGPU and ARC)
    intel-media-driver     # VA-API (iHD) userspace
    vpl-gpu-rt             # oneVPL (QSV) runtime
    vaapi-intel-hybrid
    ];
};

programs.xwayland.enable = true;

environment.variables = {
    ROC_ENABLE_PRE_VEGA = "1"; # Supposed to fix my old GPU's lack of support.
    NIXOS_OZONE_WL = "1";
};

fileSystems."/" = {
    device = "/dev/disk/by-uuid/f06f0e05-4a01-4295-a2e5-cb12f4981316";
    fsType = "ext4";
};

fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/92B7-2472";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
};

fileSystems."/mnt/media" = {
    device = "/dev/disk/by-uuid/63cd5d0f-773a-4293-83ab-4dc7eb556fdf";
    fsType = "ext4";
};

swapDevices = [ ];

}
